version: "3.3"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: Developer
    volumes:
      - sql-data:/var/opt/mssql
    ports:
      - "14330:1433"
    networks:
      - public
      - local
    hostname: mssql
    restart: "no"

volumes:
  sql-data: {}

networks:
  public:
    internal: false
  local:
    internal: true
